type UidFn = (prefix: string) => string;
type SimulateRunFn = (task: unknown, persona: unknown, iteration: number) => unknown;
export declare function buildInitialState(uid: UidFn, simulateRunFn?: SimulateRunFn): {
    projects: {
        id: string;
        name: string;
        description: string;
        created_at: string;
        updated_at: string;
    }[];
    personas: {
        id: string;
        name: string;
        description: string;
        role: string;
        segment: string;
        functional_context: string;
        usage_context: string;
        goals: string;
        motivations: string;
        needs: string;
        behaviors: string;
        pains: string;
        frictions: string;
        personality_traits: string;
        digital_environment: string;
        digital_behavior: string;
        devices: string;
        digital_level: string;
        apps_used: string;
        restrictions: string;
        attachments: string;
        status: string;
        version: number;
        created_at: string;
        updated_at: string;
    }[];
    tasks: {
        id: string;
        project_id: string;
        persona_id: string;
        type: string;
        prompt: string;
        url: string;
        success_criteria: string;
        max_steps: number;
        mcp_enabled: boolean;
        predictive_attention_enabled: boolean;
        artifacts_enabled: boolean;
        status: string;
        created_at: string;
        updated_at: string;
    }[];
    runs: unknown[];
    calibrations: {
        id: string;
        project_id: string;
        persona_id: string;
        task_id: string;
        prototype_version: string;
        human_result: string;
        synthetic_result: string;
        critical_findings: string;
        agreement: number;
        notes: string;
        created_at: string;
    }[];
};
export {};
